version: "2"

services:
  php:
    restart: never
    image: php:5.6-fpm
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    volumes:
      - ${NIFT}/php:/nift/php/
      - ${PHP_ROOT}:/var/www/html/
    entrypoint: /nift/php/entrypoint.sh
    command: php-fpm
